"""HandoffPlan: structured representation of a code-ready implementation
checklist produced by ``src.handoff_planner.HandoffPlanner``.

This module is the schema half of ARCH-5DFB393F (HandoffPlanner). The
matching planner that produces ``HandoffPlan`` instances lives in
``src.handoff_planner``. Rendering to markdown lives in
``HandoffPlan.to_markdown``.

Spec source of truth: ``docs/HANDOFF_PLANNER_OUTPUT_SPEC.md``.

Binding constraints honoured here:
    - CSTR-PLANNER-V1: no new dependencies (Pydantic v2 only — already
      in production).
    - CSTR-PLANNER-V4: fail-fast Pydantic validation.
    - CSTR-PLANNER-V5: idempotent rendering — ``to_markdown`` is
      deterministic for a given plan.
    - CSTR-PLANNER-V6: schema-stable output. Structure is fixed; only
      the system prompt may evolve.

Aesthetic amendments (from boardroom verdict 2026-05-25):
    - CREATIVE-A2: every task line is prefixed with ``[✏️ PLANNER]``
    - CREATIVE-A3: subtasks are 3-space indented with a hyphen bullet
    - CREATIVE-A4: signature footer at the end of the tasks block
    - CREATIVE-A5: task titles must be active/concise (enforced by the
      planner's system prompt; this module does not autocorrect)
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import List

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


# ════════════════════════════════════════════════════════════════════
#  Constants — render-time strings, kept here so tests can import
# ════════════════════════════════════════════════════════════════════

#: Visual cue prefixed to every planner-generated task title.
#: Required by CREATIVE-A2. Tests in tests/test_handoff_planner.py
#: assert this exact byte sequence appears in every rendered task.
PLANNER_TASK_PREFIX: str = "[✏️ PLANNER]"

#: Signature footer appended to the bottom of the rendered tasks
#: block. Required by CREATIVE-A4.
PLANNER_SIGNATURE: str = (
    "\n\n---\n*Generated by HandoffPlanner v1.0. Dark Maestro Ready.*"
)

#: Pattern for the task identifier. One uppercase letter + one or
#: more digits. e.g. ``A1``, ``B12``. Examples that must fail: ``a1``,
#: ``A``, ``1A``, ``AA1``.
_TASK_ID_PATTERN: re.Pattern[str] = re.compile(r"^[A-Z]\d+$")


# ════════════════════════════════════════════════════════════════════
#  PlanTask
# ════════════════════════════════════════════════════════════════════


class PlanTask(BaseModel):
    """A single atomic implementation task.

    Maps to one ``- [ ] **[✏️ PLANNER] <id>. <title>**`` block in the
    rendered handoff. Subtasks are flat strings (the spec does not
    nest deeper than one level — keeps the markdown predictable).
    """

    model_config = ConfigDict(frozen=False, str_strip_whitespace=False)

    id: str = Field(..., description="Task identifier, e.g. 'A1', 'B12'.")
    title: str = Field(..., min_length=1, description="One-line active task title.")
    subtasks: List[str] = Field(
        default_factory=list,
        description="Indented sub-steps under the task. May be empty.",
    )
    acceptance: str = Field(
        ...,
        min_length=1,
        description="Single-line acceptance criterion. Mandatory.",
    )
    constraints: List[str] = Field(
        default_factory=list,
        description="Binding-constraint references, e.g. ['CSTR-PLANNER-V2'].",
    )
    file_paths: List[str] = Field(
        default_factory=list,
        description="Repo-relative file paths the task touches.",
    )

    @field_validator("id")
    @classmethod
    def _validate_id(cls, v: str) -> str:
        if not _TASK_ID_PATTERN.match(v):
            raise ValueError(
                f"Task id must match {_TASK_ID_PATTERN.pattern!r}; got {v!r}"
            )
        return v

    @field_validator("title", "acceptance")
    @classmethod
    def _no_newlines_in_single_line_fields(cls, v: str) -> str:
        if "\n" in v:
            raise ValueError(
                "title and acceptance must be single-line strings"
            )
        return v


# ════════════════════════════════════════════════════════════════════
#  PlanSection
# ════════════════════════════════════════════════════════════════════


class PlanSection(BaseModel):
    """A group of related tasks rendered under ``### Section X — <name>``."""

    model_config = ConfigDict(frozen=False)

    name: str = Field(..., min_length=1, description="Section title.")
    tasks: List[PlanTask] = Field(
        ...,
        min_length=1,
        description="At least one task — empty sections are nonsensical.",
    )


# ════════════════════════════════════════════════════════════════════
#  HandoffPlan
# ════════════════════════════════════════════════════════════════════


class HandoffPlan(BaseModel):
    """The full plan, ready to render into a handoff document."""

    model_config = ConfigDict(frozen=False)

    proposal_id: str = Field(
        ...,
        min_length=1,
        description="Proposal id this plan was generated from, e.g. 'ARCH-…'.",
    )
    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="Wall-clock time the plan was emitted.",
    )
    sections: List[PlanSection] = Field(
        ...,
        min_length=1,
        description="Logical groupings of tasks. At least one section required.",
    )

    @model_validator(mode="after")
    def _unique_task_ids(self) -> "HandoffPlan":
        seen: dict[str, str] = {}
        for section in self.sections:
            for task in section.tasks:
                if task.id in seen:
                    raise ValueError(
                        f"Duplicate task id {task.id!r} "
                        f"(appears in sections {seen[task.id]!r} and {section.name!r})"
                    )
                seen[task.id] = section.name
        return self

    # ----------------------------------------------------------------
    #  Rendering
    # ----------------------------------------------------------------

    def to_markdown(self) -> str:
        """Render the plan as the contents of the ``## 🔧 Implementation Tasks`` block.

        Caller is responsible for emitting the parent ``## 🔧 Implementation Tasks``
        header — ``to_markdown`` returns only the body (sections + tasks +
        signature footer). This keeps the renderer composable with the
        wider handoff document.

        Determinism guarantee (CSTR-PLANNER-V5): identical ``HandoffPlan``
        instances render to byte-identical strings. We rely on input
        ordering — the planner is responsible for emitting sections /
        tasks / subtasks in stable order. This method does not sort.

        Returns:
            Multi-line markdown string ending with the planner signature
            footer.
        """
        lines: list[str] = []

        for section in self.sections:
            lines.append("")
            lines.append(f"### Section {self._section_letter(section)} — {section.name}")

            for task in section.tasks:
                lines.append("")
                # CREATIVE-A2: planner-prefix on every task title
                lines.append(
                    f"- [ ] **{PLANNER_TASK_PREFIX} {task.id}. {task.title}**"
                )
                # CREATIVE-A3: subtasks at 3-space indent, hyphen bullet
                for sub in task.subtasks:
                    lines.append(f"   - [ ] {sub}")
                # Specialist A1: every task has Acceptance + Constraints + Files
                lines.append(f"   - **Acceptance:** {task.acceptance}")
                if task.constraints:
                    lines.append(
                        "   - **Constraints:** "
                        + ", ".join(task.constraints)
                    )
                if task.file_paths:
                    lines.append(
                        "   - **Files:** "
                        + ", ".join(f"`{p}`" for p in task.file_paths)
                    )

        # CREATIVE-A4: signature footer
        body = "\n".join(lines).lstrip("\n")
        return body + PLANNER_SIGNATURE

    def _section_letter(self, section: PlanSection) -> str:
        """Map section index (0,1,2...) → ``A``, ``B``, ``C`` … for headers.

        This produces stable, alphabetical section labels independent of
        the section's own ``name`` field.
        """
        idx = self.sections.index(section)
        # 26 sections feels generous; if a plan exceeds that we wrap to
        # AA, AB, ... which is still deterministic and readable.
        if idx < 26:
            return chr(ord("A") + idx)
        # 26 → AA, 27 → AB, ...
        first = chr(ord("A") + (idx // 26) - 1)
        second = chr(ord("A") + (idx % 26))
        return first + second
