"""Render the kanban board to its vault markdown mirror — ARCH-DA5B0A2D (A2).

Companion to ``src.kanban_store``. Where ``kanban_store`` owns the
state, this module owns the **read-only projection** of that state into
the Obsidian-flavoured markdown that the vault displays.

Contract
--------
Pure function::

    render(BoardSnapshot) -> str

Same ``BoardSnapshot`` always produces byte-identical output (modulo the
``generated_at`` header timestamp, which is read from the snapshot, not
``datetime.now()`` — render is therefore deterministic per snapshot).

Plus one stateful helper::

    write_vault_mirror(BoardSnapshot, path=KANBAN_FILE) -> Path

Does atomic write (tmp + ``os.replace``) of the rendered markdown.
``os.replace`` is the cross-platform same-fs atomic-rename primitive and
matches what ``proposal_writer`` already uses.

Output format
-------------
The proposal mandates this exact shape (Obsidian-Kanban-plugin compatible)::

    ---
    kanban-plugin: board
    ---

    <!-- AUTO-GENERATED by kanban_renderer.py at <ISO>. Edits will be overwritten.
         Drag cards in the dashboard to move them. -->

    ## Backlog

    - [ ] DEV-… — title ^[DEV-…]
                - status: ⏳ Pending
                - severity: medium
                - created: …
                - related: [[…_PROPOSAL]]

    ## Proposal

    …

The leading ``<!-- AUTO-GENERATED -->`` HTML comment is mandatory: it's
how the dashboard-migration acceptance test ("vault edits are ignored")
detects that this file is machine-owned.

Out of scope
------------
- Writing the API endpoints that trigger render (A3).
- Slimming ``kanban_processor`` to delegate here (A5).
- The one-shot migration that backfills the SQLite (B1).
"""

from __future__ import annotations

import logging
import os
import tempfile
from pathlib import Path
from typing import Iterable, Mapping, Optional

from src.kanban_store import (
    CANONICAL_COLUMNS,
    BoardSnapshot,
    Card,
)
from src.paths import KANBAN_FILE

logger = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════════
#  Constants
# ════════════════════════════════════════════════════════════════════

#: Header comment marking the file as machine-owned. The acceptance
#: criterion in the proposal §"Vault mirror is generated" looks for the
#: exact prefix ``<!-- AUTO-GENERATED by kanban_renderer.py``. If you
#: change this prefix, update the proposal's acceptance check too.
AUTOGEN_PREFIX: str = "<!-- AUTO-GENERATED by kanban_renderer.py"

#: Header line emitted by Obsidian's Kanban plugin. Without it, Obsidian
#: renders this file as plain markdown instead of as a kanban board.
KANBAN_PLUGIN_HEADER: str = "kanban-plugin: board"

#: Map from canonical (lowercase) column name → Title Case header.
#: Matches the existing vault file (verified via ``Dev-KanBan.md`` head).
_COLUMN_TITLES: Mapping[str, str] = {
    "backlog": "Backlog",
    "proposal": "Proposal",
    "beta testing": "Beta Testing",
    "alpha polish": "Alpha Polish",
    "finalized": "Finalized",
    "deployed": "Deployed",
}

#: Substatus → user-visible status emoji+label, mirroring the existing
#: vault file format. When ``Card.substatus`` is None we fall back to
#: ⏳ Pending so the existing Obsidian visual language is preserved.
#:
#: This is a render concern only; the canonical substatus values live in
#: ``kanban_store``. Anything we don't recognise renders verbatim.
_SUBSTATUS_LABELS: Mapping[str, str] = {
    "planning":          "📋 Planning",
    "execution.coding":  "🔨 Coding",
    "execution.testing": "🧪 Testing",
    "review":            "🔍 Review",
    "blocked":           "⛔ Blocked",
}


# ════════════════════════════════════════════════════════════════════
#  Public API
# ════════════════════════════════════════════════════════════════════


def render(snapshot: BoardSnapshot) -> str:
    """Render a ``BoardSnapshot`` to Obsidian-Kanban-plugin markdown.

    Pure function: given the same input, returns byte-identical output.
    Columns are emitted in :data:`~src.kanban_store.CANONICAL_COLUMNS`
    order — empty columns get their header but no cards.

    The ``generated_at`` from the snapshot is embedded in the autogen
    header so that ``write_vault_mirror`` can do a content-equality
    short-circuit if nothing changed.
    """
    parts: list[str] = []

    # Frontmatter — Obsidian Kanban plugin requires this exact block.
    parts.append("---")
    parts.append(KANBAN_PLUGIN_HEADER)
    parts.append("---")
    parts.append("")  # blank line between frontmatter and autogen marker
    parts.append(
        f"{AUTOGEN_PREFIX} at {snapshot.generated_at}. "
        "Edits will be overwritten. Drag cards in the dashboard to move them. -->"
    )
    parts.append("")

    # Columns in canonical order. We index by name so explicit empty
    # columns still render (acceptance criterion: dashboard renders 6).
    by_name = {col.name: col for col in snapshot.columns}
    for canonical_name in CANONICAL_COLUMNS:
        title = _COLUMN_TITLES[canonical_name]
        parts.append(f"## {title}")
        parts.append("")

        column = by_name.get(canonical_name)
        if column is None or not column.cards:
            parts.append("")
            continue

        for card in column.cards:
            parts.extend(_render_card_lines(card))

        parts.append("")

    # Trailing newline so the file looks well-terminated to ``wc -l``
    # and to git's CRLF / final-newline checks.
    return "\n".join(parts) + "\n"


def write_vault_mirror(
    snapshot: BoardSnapshot,
    path: Optional[Path] = None,
) -> Path:
    """Atomically write the rendered ``snapshot`` to the vault kanban file.

    Args:
        snapshot: The board state to render.
        path: Override destination. Defaults to ``src.paths.KANBAN_FILE``.
            Tests pass ``tmp_path / "Dev-KanBan.md"`` here.

    Returns:
        The path written.

    Behaviour:
        - Creates parent directory if missing.
        - Skips the write entirely if the rendered bytes match what's
          already on disk (saves the vault from spurious mtime bumps and
          gives proposal_sync nothing to react to).
        - Otherwise writes via ``tempfile.NamedTemporaryFile`` +
          ``os.replace`` so partial writes are never visible.
    """
    target = (path or KANBAN_FILE).resolve()
    target.parent.mkdir(parents=True, exist_ok=True)

    rendered = render(snapshot)

    # Short-circuit: skip the write if content is unchanged. This is the
    # contract that lets us call ``write_vault_mirror`` after every
    # transition without thrashing the file's mtime.
    if target.exists():
        try:
            existing = target.read_text(encoding="utf-8")
            if existing == rendered:
                logger.debug("kanban_renderer: no change for %s, skipping write", target)
                return target
        except OSError as exc:
            # Read failures are non-fatal — we proceed to the write and
            # let that surface a clearer error.
            logger.warning("kanban_renderer: could not read existing %s: %r", target, exc)

    # Atomic write: tempfile in the same dir, then os.replace.
    # NamedTemporaryFile keeps the file open in the same dir so os.replace
    # is a same-filesystem rename (atomic on Windows + POSIX).
    fd, tmp_path_str = tempfile.mkstemp(
        prefix=".tmp_dev-kanban_",
        suffix=".md",
        dir=str(target.parent),
    )
    tmp_path = Path(tmp_path_str)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(rendered)
        os.replace(tmp_path, target)
    except Exception:
        # Cleanup on failure; never leak the .tmp_ file.
        try:
            if tmp_path.exists():
                tmp_path.unlink()
        except OSError:
            pass
        raise

    return target


# ════════════════════════════════════════════════════════════════════
#  Card rendering — kept separate so it's individually testable
# ════════════════════════════════════════════════════════════════════


def _render_card_lines(card: Card) -> Iterable[str]:
    """Emit the markdown lines for one card.

    Format (mirrors the existing vault file)::

        - [ ] DEV-… — <title> ^[DEV-…]
                    - status: ⏳ Pending
                    - severity: medium
                    - related: [[…_PROPOSAL]]

    Indentation: 12 spaces (legacy choice — Obsidian Kanban plugin
    parses this as "metadata of the parent task"). We honour it.

    Block reference (``^[…]``) is emitted ONCE — the existing file has
    them duplicated 12+ times due to a bug in the old appender. The new
    renderer fixes that by simply not repeating.
    """
    title_text = card.title or _fallback_title(card)
    block_ref = _block_ref(card.proposal_id)

    yield f"- [ ] {card.proposal_id} — {title_text} {block_ref}"

    # Status line. We always emit one — the old format never lacks it.
    status_label = _render_status(card)
    yield f"            - status: {status_label}"

    # Severity, only when known.
    if card.severity:
        yield f"            - severity: {card.severity}"

    # Origin, only when known.
    if card.origin:
        yield f"            - origin: {card.origin}"

    # Created timestamp (date only — matches existing file).
    if card.created_ts:
        yield f"            - created: {_iso_to_kanban_date(card.created_ts)}"

    # Last-updated timestamp.
    if card.updated_ts and card.updated_ts != card.created_ts:
        yield f"            - updated: {_iso_to_kanban_date(card.updated_ts)}"

    # Cross-link back to the proposal file. We rebuild the wiki-link from
    # the proposal_id rather than trusting any external field, so this
    # always points at the right file regardless of how the card was
    # created.
    yield f"            - related: [[{card.proposal_id}_PROPOSAL]]"


def _fallback_title(card: Card) -> str:
    """When a card has no title, synthesise a placeholder so the rendered
    line stays readable. We avoid an empty title — the dashboard UI
    would render a blank card."""
    return f"({card.prefix} card)"


def _block_ref(proposal_id: str) -> str:
    """Obsidian block-ref label for a proposal id.

    Existing vault file uses the form ``^[ARCH-20260524011510-5DFB393F]``
    (no second hyphen — Obsidian block-ref-id charset doesn't allow
    multiple hyphens cleanly). We construct it the same way for parity.
    """
    # The historical format used ``^[<id-with-only-first-hyphen>]`` — let's
    # check the vault for the actual convention by looking at the
    # placeholder in the existing file:
    #   ^[ARCH2026052322340378D36EDB]   (no hyphens at all)
    # We follow that convention.
    return f"^[{proposal_id.replace('-', '')}]"


def _render_status(card: Card) -> str:
    """Map ``card.substatus`` to a user-visible status label.

    When ``substatus`` is None we render ⏳ Pending (matches the legacy
    format). When ``substatus`` is in :data:`_SUBSTATUS_LABELS` we use
    the friendly label; otherwise we emit it verbatim so callers that
    use new substatus values aren't silently dropped.
    """
    if not card.substatus:
        return "⏳ Pending"
    return _SUBSTATUS_LABELS.get(card.substatus, card.substatus)


def _iso_to_kanban_date(iso_ts: str) -> str:
    """Trim ``2026-05-25T13:45:30.123456+00:00`` → ``2026-05-25``.

    Defensive: if parsing fails we return the original string rather
    than dropping data. The render is best-effort cosmetic.
    """
    if not iso_ts:
        return ""
    # Anything before the 'T' is the date; isoformat is consistent enough.
    if "T" in iso_ts:
        return iso_ts.split("T", 1)[0]
    return iso_ts


__all__ = [
    "AUTOGEN_PREFIX",
    "KANBAN_PLUGIN_HEADER",
    "render",
    "write_vault_mirror",
]
